#!/bin/bash

TARGET_BINARY=$1
SEED_INPUT_FILE=$2
ARG_LIST=$3
TARGET_WRITE_ADDRESS=$4
TARGET_WRITE_VALUE=$5
SOLUTION_INPUT_FILE=$6

python3 ./naive_solution.py \
  $TARGET_BINARY \
  $SEED_INPUT_FILE \
  $ARG_LIST \
  $TARGET_WRITE_ADDRESS \
  $TARGET_WRITE_VALUE \
  $SOLUTION_INPUT_FILE
